# Generated by Django 3.2.5 on 2022-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
